### ISSUE TITLE
The Good Docs Project should have a CODE_OF_CONDUCT.md file, and template(s) for a code of conduct

### ISSUE THREAD

**Issue by ScriptAutomate** [thegooddocsproject/templates#158]
What is often found as standard in open-source repositories is a `CODE_OF_CONDUCT.md` file. Not only may it be a good idea for the repositories that are open-source under The Good Docs Project to have one, but it also may be a good idea to have a template.

Fortunately, this work may already be done for us by [Contributor Covenant](https://www.contributor-covenant.org/), which provides a template for a **Code of Conduct**. It has been adopted already by many other open-source projects such as Jekyll, Node.js, and others such as the CNCF (around Jenkins, Kubernetes, etc.):
- [Contributor Coveneant: Latest Version, v2.0](https://www.contributor-covenant.org/version/2/0/code_of_conduct/)
  - [Markdown Format](https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md)

We could adopt the same into a `CODE_OF_CONDUCT.md`? We could also have templates of the Contributor Covenant and other code of conducts within a template subdir? That, or a file that links to several example code of conduct templates hosted/managed by other projects out there?

For more info:
- https://docs.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project
- https://opensource.guide/code-of-conduct/
- https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/
- The Django Code of Conduct: https://www.djangoproject.com/conduct/
- Code Fellows code of conduct: https://github.com/codefellows/code-of-conduct

**Comment by barbaricyawps** [comment]
I totally like this idea. Some items to consider:

- Would we need to assign any kind of attribution for it or are there any licensing issues to worry about?
- How stable is the Contributor Covenant COC, meaning how regularly it is modified. If they update, how can we ensure that we inherit their changes?

**Comment by ScriptAutomate** [comment]
## Would we need to assign any kind of attribution for it or are there any licensing issues to worry about?

Usually, for attribution, using the Contributor Covenant includes this at the bottom:

---

## Attribution

This Code of Conduct is adapted from the [Contributor Covenant][homepage],
version 2.0, available at
https://www.contributor-covenant.org/version/2/0/code_of_conduct.html.

Community Impact Guidelines were inspired by [Mozilla's code of conduct
enforcement ladder](https://github.com/mozilla/diversity).

[homepage]: https://www.contributor-covenant.org

For answers to common questions about this code of conduct, see the FAQ at
https://www.contributor-covenant.org/faq. Translations are available at
https://www.contributor-covenant.org/translations.

---

Which is included in the Markdown source found here:
- https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md

This would fulfill their licensing requirement:

> _The Contributor Covenant is released under the [Creative Commons Attribution 4.0 International Public License](https://github.com/ContributorCovenant/contributor_covenant/blob/release/LICENSE.md), which requires that attribution be included._

## How stable is the Contributor Covenant COC, meaning how regularly it is modified? If they update, how can we ensure that we inherit their changes?

Contributor Covenant has **349** unique contributors to the repository, so far, and looks pretty active:
- https://github.com/ContributorCovenant/contributor_covenant

As for inheriting changes when updates happen, that's a good question. I suppose it would involve a review, and then an update? The Good Docs Project would probably want one main `CODE_OF_CONDUCT.md` file located in one repository, and then have every other open sourced repo under the org have a `CODE_OF_CONDUCT.md` file that links back to it, to ensure no need to keep all open sourced projects up-to-date. This seems to be what orgs like the CNCF are doing in order to just have to update one file to keep them all updated.

**Comment by ScriptAutomate** [comment]
Also, this may be how TheGoodDocs project can cover all open-source repos with standard templates around their code of conduct, issue templates, etc:
- https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#about-default-community-health-files

And then we should probably document it so other people are aware they can do the same thing in their own orgs! ;D

**Comment by mgan59** [comment]
Want to make sure I understand what it is we are looking to address.

1. We lack a `CODE_OF_CONDUCT.md` in our repos?   This is sorta true.  We have [CodeOfConduct](https://github.com/thegooddocsproject/governance/blob/master/CodeOfConduct.md) inside of our `governance` repo.  Which is linked to from our [webite/community-section](https://thegooddocsproject.dev/community.html).  Would probably help to rename the file to match the convention github would prefer which is `CODE_OF_CONDUCT.md` and not `CodeOfConduct.md`.  Question is do we want to drop in a `CODE_OF_CONDUCT.md` into every repo, even if that repo isn't necessarily a front-facing repo?  Do we have the same version across all repos?  Think there is a discussion here.

2. Strategy for creating Templates? Mentioned above the url for [adding-a-code-of-conduct-to-your-project](https://docs.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project) which illustrates the UI/Workflow to add a templated COC from within Github.
![Screen Shot 2020-09-15 at 8 29 31 AM](https://user-images.githubusercontent.com/89339/93210461-a611e100-f72d-11ea-817b-6d9413533294.png)
> Looks like they support ContributorCovenant & _Citizen Code of Conduct_ which the site doesn't load.
The above approach makes sense I think for one/off repos and projects.  But if you have an organization with 50+ repos this becomes time-consuming and tedious.  So having a `cli` tool in place makes this more manageable.  But updating and modifying templates with this tooling will take engineering effort.

---

__Thoughts Going Forward for our `CODE_OF_CONDUCT`__

What I think might make sense, we have one `CODE_OF_CONDUCT.md` that is the single-source of truth that lives in a repo (`governance` is fine).  And for all other repositories (templates, incubator, etc..) we have a `CODE_OF_CONDUCT.md` in those as well, but we have those files a _REFERENCE TO LINK BACK_ to the single `CODE_OF_CONDUCT.md` inside of `governance`.  That way we are only ever maintaining __one__ COC.

If it comes to a time, when different repositories need their own COC that isn't aligned with the organization as a whole, we can cross that bridge when we get there :wink:


__Thoughts Going Forward for our Template-Tooling__

This is a much larger conversation around what we want our tooling-chain to look like in the end.  And there are many question here.  What is the purpose of this tooling (Jobs-To-Be-Done)?  Is it one tool or many tools?  What technology choices do we adopt as that will affect its adoption.

---

## Actionable / Followups -- PR Work

I think we should at least rename the `CodeOfConduct.md` in _governance_ to `CODE_OF_CONDUCT.md` and update the marketing-site's url/link back to it (the urls are most likely case-sensitive).

If we are agreed on the _reference to link back_ strategy we can drop other `CODE_OF_CONDUCT.md` files into all our other repos (Templates, Incubator, the marketing-site repo, etc...)

**Comment by barbaricyawps** [comment]
I could have misunderstood what @ScriptAutomate is proposing, but I think he's suggesting we provide a template for a code of conduct since a COC would definitely fit into the definition of a "minimum viable docset" for a new open source project.

**Comment by jaredmorgs** [comment]
No, I believe the intent is for the Good Docs Project to have a
centrally-managed CoC for our own needs, not necessarily a template for a
CoC for other users to consume.

Having guidelines for creating a CoC would be a good addition, but is out
of the scope of this issue scope.

**Comment by barbaricyawps** [comment]
It's worth mentioning that we recently added a template for Communication Guidelines to the incubator, which seems similar to this proposal:

- https://github.com/thegooddocsproject/incubator/blob/master/about-communications.md
- https://github.com/thegooddocsproject/incubator/blob/master/template-communications.md

**Comment by jaredmorgs** [comment]
@barbaricyawps does the Comms Guidelines mean that this issue is resolved, or are there some edge cases left?

**Comment by barbaricyawps** [comment]
It's not yet resolved, @jaredmorgs . In fact, it has recently come to my attention that this is an even higher priority issue than I thought. I plan to work on this issue this week.

**Comment by ScriptAutomate** [comment]
Ah, maybe this issue truly belongs in the [`governance` repo](https://github.com/thegooddocsproject/governance)? If so, I think we should consider org-wide (applying to TheGoodDocs projects in general) saving of files like `CODE_OF_CONDUCT.md` into a `.github` repository, as detailed here:
- https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file

The problem of having a `governance` repo dedicated to storing a file like this is that people may be exposed to a single repository and not be aware of the wider org-related items (such as a code of conduct), unless they are explicitly directed to the governance repo. Using the `.github` repo, at the org-level, automatically populates a file within repositories throughout the org where the files are not present. It is either this route, or needing to create linkback files across repositories that point to master files residing in the `governance` repo, in order to avoid needing to update files everywhere each time a revision is made.

**Comment by ScriptAutomate** [comment]
I have created https://github.com/thegooddocsproject/governance/issues/11 in the `governance` repository.

I also made https://github.com/thegooddocsproject/governance/pull/10 to change the `CodeOfConduct.md` to the `CODE_OF_CONDUCT.md` naming convention.

**Comment by barbaricyawps** [comment]
Resolved. Closing!
